# Generated by Django 5.1.6 on 2025-03-04 19:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Country",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("country", models.CharField(default="Unknown", max_length=100)),
                ("continent", models.CharField(default="Unknown", max_length=100)),
                ("capital", models.CharField(default="Unknown", max_length=100)),
                ("abbrev", models.CharField(default="Unk", max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name="Fact",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fact", models.CharField(default="Unknown", max_length=500)),
                ("source", models.CharField(default="Unknown", max_length=300)),
                (
                    "country",
                    models.ForeignKey(
                        default=1,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="api.country",
                    ),
                ),
            ],
        ),
    ]
