# Generated by Django 5.1.6 on 2025-03-04 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Country",
            fields=[
                ("country_id", models.IntegerField(primary_key=True, serialize=False)),
                ("country", models.CharField(max_length=100)),
                ("continent", models.CharField(max_length=100)),
                ("abbrev", models.CharField(max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name="Fact",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("text", models.TextField()),
            ],
        ),
    ]
